/**
 * Copyright 2007 Matthew Hillsdon
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package net.hillsdon.reviki.vc;

import java.util.Date;

import junit.framework.TestCase;

public class TestChangeInfo extends TestCase {

  public void testGetDescriptionStripsURL() {
    ChangeInfo changeInfo = new ChangeInfo("MyPage", "MyPage", "mth", new Date(), 1, "Twiddled frobs.\nhttp://www.example.com/wiki/MyPage\n", StoreKind.PAGE, ChangeType.MODIFIED);
    assertEquals("Twiddled frobs.", changeInfo.getDescription());
  }
 
  public void testMinorEditPrefixIgnored() {
    ChangeInfo changeInfo = new ChangeInfo("MyPage", "MyPage", "mth", new Date(), 1, "[minor edit]\nTwiddled frobs.\nhttp://www.example.com/wiki/MyPage\n", StoreKind.PAGE, ChangeType.MODIFIED);
    assertEquals("Twiddled frobs.", changeInfo.getDescription());
  }
  
  public void testAutoGeneratedMessagesNotReturnedInDescription() {
    ChangeInfo changeInfo = new ChangeInfo("MyPage", "MyPage", "mth", new Date(), 1, "[svnwiki commit]\nhttp://www.example.com/wiki/MyPage\n", StoreKind.PAGE, ChangeType.MODIFIED);
    assertEquals("None", changeInfo.getDescription());
  }
  
}

